#!/usr/bin/env bash
#
#   zoek?
#   Dutch, weak verb, present tense
#   to search, look for, to seek
#   
#   Search for native, flatpak and snap packages with one command
#   run this script with the search string as argurment
#   example:
#   zoek packagename    
#   screenshot:
#   https://i.imgur.com/s5gFSzP.png
#   instructions:
#   Save this file as /usr/bin/zoek
#   Set execute permissions: chmod +x /usr/bin/zoek
#   Currently works with linux distributions: Solus, Arch, Debian, Fedora, CentOS, Rocky Linux, AlmaLinux, Alpine, Void, Chimera

source /etc/os-release
declare -A osInfo;
osInfo[/usr/bin/eopkg]=eopkg
osInfo[/usr/bin/apt-cache]=apt-cache
osInfo[/usr/bin/dnf]=fedora
osInfo[/usr/bin/pacman]=arch
osInfo[/sbin/apk]=alpine
osInfo[/usr/bin/xbps-query]=void
echo 
for f in ${!osInfo[@]}
do
    if [[ -f $f ]];then
        echo Package manager: ${osInfo[$f]} on $PRETTY_NAME

echo Searching for native packages...
$f search $1
#dirtyhackforarch, arch users are used to it anyway
test -f /usr/bin/dnf && $f -Ss $1
echo 

echo "looking for snap packages..."
snap search $1
echo 

echo "flatpak maybe?"
flatpak search $1
echo 

echo "do u want check appimage?"
curl -fsSL https://raw.githubusercontent.com/ivan-hc/AM/refs/heads/main/programs/x86_64-appimages | grep $1
fi
done
echo
